FROM microsoft/dotnet:2.0.0-sdk-nanoserver
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

ENV EnvironmentVariable-FromDockerfile FromDockerfile
# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/EnvironmentVariablesTarget.dll"]esTarget.dll"]